calculate pitch
athena-team/athena pull request #30
Opened 2020-01-14 07:29 UTC by aishinchi

Add post-process pitch features to athena.transform. Default params produce 3-dimensional pitch features consisting of (pov-feature, pitch-feature, delta-pitch-feature).

2020-01-14 09:31 UTC, tjadamlee requested changes
Please only submit the necessary change related to the pitch

2020-01-14 09:31 UTC, tjadamlee commented on athena/data/datasets/speech_recognition.py
> +        "vocab_file": "examples/asr/hkust/data/vocab",
This should not be included in current commit ?

2020-01-14 11:50 UTC, tjadamlee commented
@Some-random @leixiaoning 
please help test this

2020-01-15 04:15 UTC, Some-random commented
> @Some-random @leixiaoning
> please help test this

Running HKUST benchmark again with 80 dim FBANK + 3 dim Pitch right now

2020-01-22 14:17 UTC, tjadamlee commented
@aishinchi @Some-random 
if currently it is not finished, please close this pr
You can re push after evaluated

2020-01-27 02:22 UTC, tjadamlee commented
please check, and then re push

2020-01-27 02:22 UTC, closed without merging