add rnnlm decoding
athena-team/athena pull request #5
Opened 2019-12-27 05:29 UTC by cookingbear

2019-12-27 06:24 UTC, tjadamlee requested changes

2019-12-27 06:24 UTC, tjadamlee commented on athena/data/datasets/speech_recognition.py
> +        if "speakers" not in headers.split("\t"):
we use speaker not speakers

2019-12-27 07:35 UTC, Some-random commented on examples/asr/aishell/rnnlm.json
> +    "num_layer": 4,
we still need to test the performance of 4 layer rnnlm verses 2 layer rnnlm, but it's ok for now

2019-12-27 09:29 UTC, Some-random approved these changes

2019-12-30 07:07 UTC, tjadamlee approved these changes

2019-12-30 07:08 UTC, merged